apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yamcs.fullname" . }}
  labels:
    {{- include "yamcs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yamcs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yamcs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: yamcs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh"]
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
            - name: MAVEN_HTTPS_PROXY
              value: {{ .Values.env.MAVEN_HTTPS_PROXY | quote }}
            - name: HTTPS_PROXY
              value: {{ .Values.env.HTTPS_PROXY | quote }}
            - name: HTTP_PROXY
              value: {{ .Values.env.HTTP_PROXY | quote }}
            - name: NO_PROXY
              value: {{ .Values.env.NO_PROXY | quote }}
            - name: DEPLOYMENT_ENVIRO
              value: {{ .Values.env.DEPLOYMENT_ENVIRO | quote }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "yamcs.fullname" . }}-entrypoint
            defaultMode: 0755
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
